package com.pheiffware.lib.and.input;

import com.pheiffware.lib.geometry.Transform2D;

/**
 * Created by Steve on 3/18/2016.
 */
public interface TouchTransformListener
{
    /**
     * Called whenever a pointer moves on the screen.  Newly added pointers are processed, but do not generate events.
     *
     * @param numPointers The number of pointers on the screen while this transform happened
     * @param transform The transform generated by the last pointer motion event.
     */
    void touchTransformEvent(int numPointers, Transform2D transform);
}
